default_platform(:ios)

platform :ios do
  desc "Upload to App Store using p8 key"
  lane :upload do
    api_key = app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
      key_filepath: "AuthKey_QMN99784M3.p8",  # должен лежать в fastlane/
      in_house: false
    )

    deliver(
      ipa: "../build/ios/ipa/plantmana_test.ipa",
      skip_screenshots: true,
      skip_metadata: true,
      api_key: api_key
    )
  end
end
